# Generated by Django 5.0.1 on 2024-08-09 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('worldcity', models.BooleanField(default=False)),
                ('megacity', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('meganame', models.CharField(max_length=100)),
                ('idc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityPM25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.IntegerField(default=False)),
                ('pm25', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('init_date', models.DateField(default=False)),
                ('forecast_time', models.CharField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='country_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_gid', models.CharField(max_length=10)),
                ('adm0_id', models.IntegerField()),
                ('adm0_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='district_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_gid', models.CharField(max_length=10)),
                ('adm0_id', models.IntegerField()),
                ('adm0_name', models.CharField(max_length=100)),
                ('adm1_gid', models.CharField(max_length=10)),
                ('adm1_id', models.IntegerField()),
                ('adm1_name', models.CharField(max_length=100)),
                ('adm2_gid', models.CharField(max_length=10)),
                ('adm2_id', models.IntegerField()),
                ('adm2_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='province_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_gid', models.CharField(max_length=10)),
                ('adm0_name', models.CharField(max_length=100)),
                ('adm1_gid', models.CharField(max_length=10)),
                ('adm1_id', models.IntegerField()),
                ('adm1_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PM25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_lvl', models.CharField(max_length=10)),
                ('area_id', models.IntegerField(default=False)),
                ('area_name', models.CharField(max_length=100)),
                ('min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('init_date', models.DateField()),
                ('forecast_time', models.DateTimeField()),
            ],
            options={
                'unique_together': {('adm_lvl', 'area_id', 'init_date', 'forecast_time')},
            },
        ),
    ]
