# Generated by Django 5.0.1 on 2024-06-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('worldcity', models.BooleanField(default=False)),
                ('megacity', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('meganame', models.CharField(max_length=100)),
                ('idc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityPM25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_pm25', models.DateField()),
                ('time_pm25', models.CharField(max_length=10)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
            ],
        ),
    ]
