# Generated by Django 5.0.1 on 2024-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cityno2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm24h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_lvl', models.CharField(max_length=10)),
                ('area_id', models.IntegerField(default=False)),
                ('area_name', models.CharField(max_length=100)),
                ('firmcount', models.IntegerField(default=False)),
                ('init_date', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Firm48h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_lvl', models.CharField(max_length=10)),
                ('area_id', models.IntegerField(default=False)),
                ('area_name', models.CharField(max_length=100)),
                ('firmcount', models.IntegerField(default=False)),
                ('init_date', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Firmday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_lvl', models.CharField(max_length=10)),
                ('area_id', models.IntegerField(default=False)),
                ('area_name', models.CharField(max_length=100)),
                ('firmcount', models.IntegerField(default=False)),
                ('init_date', models.DateField(default=False)),
            ],
        ),
    ]
