# Generated by Django 5.0.1 on 2024-06-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_citypm25'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citypm25',
            name='date_pm25',
        ),
        migrations.RemoveField(
            model_name='citypm25',
            name='time_pm25',
        ),
        migrations.AddField(
            model_name='citypm25',
            name='forecast_time',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='citypm25',
            name='init_date',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='citypm25',
            name='pm25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
