# Generated by Django 5.0.1 on 2024-06-18 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_citypm25_date_pm25_remove_citypm25_time_pm25_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypm25',
            name='forecast_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citypm25',
            name='init_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
