# Generated by Django 5.0.1 on 2024-08-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_firm24h_firm48h_firmday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firmday',
            new_name='Firmsingle',
        ),
    ]
