# Generated by Django 5.0.1 on 2024-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_firmday_firmsingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_table',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='country_table',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='province_table',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='province_table',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
