# Generated by Django 5.0.1 on 2024-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_citypm25_forecast_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypm25',
            name='forecast_time',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='citypm25',
            name='init_date',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
