# Generated by Django 5.0.1 on 2024-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_citypm25_forecast_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypm25',
            name='idc',
            field=models.IntegerField(default=False),
        ),
    ]
